language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

script: phpunit --coverage-text